### ISSUE TITLE
Unclear additional_data behavior of different event's types. 

### ISSUE THREAD

**Issue by Yaroslavzev** [umbrellio/table_sync#27]
Current implementation intends that update and destroy events must have same attribute fields.
As consequence,  dirty `additional_data` appears.
I think it will be useful if it is possible to create `additional_data` for each type of event separately.

Below case that shows dirty `additional_data`.
Let's imagine that receiver get update-event with attributes:
```json
   {
     id: 12,
     name: "kek"
     ...,
   }
```
and destroy_event with:
```json
   {
     id: 12,
   }
```
receiver is:
```ruby
receive "Model", to_table: :models do
  additional_data do |current_row:|
    next {} if current_row.keys.count == 1 # destroy condition
    super_name = current_row[:name].upcase
    {
      name: super_name
    }
  end
  on_destroy do |attributes:, target_keys:| # rubocop:disable Lint/UnusedBlockArgument
    Model[attributes[:id]].update
  end
end
```

**Comment by 0exp** [comment]
**IMHO**

In this case we should provide a variative way to define `additional_data`: an optional attribute `ignore_on: [event_type, event_type]` to ignore `additional_data`;

Concept:

```ruby
additional_data(ignore_on: :destroy) do |current_row:|
  ...
end
```

**Comment by 7dr1v3** [comment]
TS configs has option `events:`

```
receive "Model", to_table: :models, events: :update do
  ....
end

receive "Model", to_table: :models, events: :destroy do
  ....
end
```

**Comment by 7dr1v3** [comment]
propose to close this question

**Comment by 0exp** [comment]
:ok_hand:
